"""PR data normalization helpers for transforming GitHub CLI JSON into API shapes."""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path
from typing import Any

PR_JSON_FIELDS = ",".join(
    [
        "additions",
        "author",
        "baseRefName",
        "body",
        "comments",
        "deletions",
        "files",
        "headRefName",
        "isDraft",
        "labels",
        "latestReviews",
        "mergeStateStatus",
        "mergeable",
        "number",
        "reviewDecision",
        "state",
        "statusCheckRollup",
        "title",
        "updatedAt",
        "url",
    ]
)

PR_STATUS_LABELS = {
    "needs_review": "Needs review",
    "approved": "Approved",
    "merged": "Merged",
    "refused": "Refused",
}


def _author_login(value: Any) -> str:
    if isinstance(value, dict):
        return str(value.get("login") or value.get("name") or "Unknown")
    return str(value or "Unknown")


def _author_is_bot(value: Any) -> bool:
    if not isinstance(value, dict):
        return False
    login = str(value.get("login") or "").lower()
    return bool(value.get("is_bot")) or login.endswith("[bot]") or login.endswith("-bot") or login == "github-actions"


def _contains_ai_marker(body: str) -> bool:
    normalized = body.lower()
    return any(
        marker in normalized
        for marker in (
            "personagent ai analysis",
            "ai analysis",
            "ai review",
            "[ai]",
            "generated by ai",
        )
    )


def _pr_status(item: dict[str, Any]) -> str:
    state = str(item.get("state") or "").upper()
    review_decision = str(item.get("reviewDecision") or "").upper()
    merge_state = str(item.get("mergeStateStatus") or "").upper()
    mergeable = str(item.get("mergeable") or "").upper()
    if state == "MERGED":
        return "merged"
    if state == "CLOSED" or review_decision == "CHANGES_REQUESTED" or merge_state == "DIRTY" or mergeable == "CONFLICTING":
        return "refused"
    if review_decision == "APPROVED":
        return "approved"
    return "needs_review"


def _status_from_review_state(state: str) -> str | None:
    normalized = state.upper()
    if normalized == "APPROVED":
        return "approved"
    if normalized == "CHANGES_REQUESTED":
        return "refused"
    if normalized in {"COMMENTED", "REVIEW_REQUIRED", "PENDING"}:
        return "needs_review"
    return None


def _relative_time_label(value: Any) -> str:
    if not isinstance(value, str) or not value:
        return "recently"
    raw = value.replace("Z", "+00:00")
    try:
        updated = datetime.fromisoformat(raw)
    except ValueError:
        return value
    if updated.tzinfo is None:
        updated = updated.replace(tzinfo=UTC)
    seconds = max(0, int((datetime.now(UTC) - updated).total_seconds()))
    if seconds < 60:
        return "just now"
    minutes = seconds // 60
    if minutes < 60:
        return f"{minutes}m ago"
    hours = minutes // 60
    if hours < 24:
        return f"{hours}h ago"
    days = hours // 24
    if days < 30:
        return f"{days}d ago"
    months = days // 30
    if months < 12:
        return f"{months}mo ago"
    return f"{months // 12}y ago"


def _first_body_paragraph(body: Any, title: str) -> str:
    if not isinstance(body, str) or not body.strip():
        return title
    lines: list[str] = []
    for line in body.splitlines():
        stripped = line.strip()
        if not stripped:
            if lines:
                break
            continue
        if stripped.startswith("#"):
            continue
        if stripped.startswith(("-", "*")):
            stripped = stripped.lstrip("-* ").strip()
        if stripped:
            lines.append(stripped)
        if len(" ".join(lines)) > 220:
            break
    summary = " ".join(lines).strip() or title
    return summary[:260]


def _check_summary(items: Any) -> tuple[str, bool]:
    if not isinstance(items, list) or not items:
        return "No checks", False
    failing = 0
    pending = 0
    passing = 0
    for item in items:
        if not isinstance(item, dict):
            continue
        conclusion = str(item.get("conclusion") or "").upper()
        status = str(item.get("status") or item.get("state") or "").upper()
        if conclusion in {"FAILURE", "CANCELLED", "TIMED_OUT", "ACTION_REQUIRED"}:
            failing += 1
        elif conclusion in {"SUCCESS", "NEUTRAL", "SKIPPED"}:
            passing += 1
        elif status and status not in {"COMPLETED", "SUCCESS"}:
            pending += 1
        else:
            pending += 1
    total = passing + failing + pending
    if total == 0:
        return "No checks", False
    if failing:
        return f"{failing} failing / {total} checks", True
    if pending:
        return f"{pending} pending / {total} checks", False
    return f"{passing} passing", False


def _risk_label(item: dict[str, Any], status: str, checks_failing: bool) -> str:
    additions = int(item.get("additions") or 0)
    deletions = int(item.get("deletions") or 0)
    files = item.get("files") if isinstance(item.get("files"), list) else []
    changed = additions + deletions
    if status == "refused" or checks_failing or changed >= 1000 or len(files) >= 20:
        return "High"
    if status == "needs_review" or changed >= 250 or len(files) >= 6:
        return "Medium"
    return "Low"


def _pr_file(item: Any, index: int) -> dict[str, Any] | None:
    if not isinstance(item, dict):
        return None
    path = str(item.get("path") or item.get("filename") or "")
    if not path:
        return None
    additions = int(item.get("additions") or 0)
    deletions = int(item.get("deletions") or 0)
    if additions and deletions:
        change_type = "modified"
    elif additions:
        change_type = "added"
    elif deletions:
        change_type = "deleted"
    else:
        change_type = "modified"
    return {
        "id": f"file-{index}-{path.replace('/', '-')}",
        "path": path,
        "changeType": change_type,
        "additions": additions,
        "deletions": deletions,
        "summary": f"{change_type.title()} file from GitHub PR metadata.",
        "lines": [],
    }


def _pr_comment(item: Any, index: int) -> dict[str, Any] | None:
    if not isinstance(item, dict):
        return None
    body = str(item.get("body") or "").strip()
    if not body:
        return None
    author = item.get("author")
    source = "ai" if _author_is_bot(author) or _contains_ai_marker(body) else "human"
    return {
        "id": str(item.get("id") or item.get("url") or f"comment-{index}"),
        "kind": "ai_review" if source == "ai" else "human_review",
        "source": source,
        "author": _author_login(author),
        "body": body,
        "createdAt": item.get("createdAt") or item.get("updatedAt"),
        "url": item.get("url"),
        "status": None,
    }


def _pr_review_comment(item: Any, index: int) -> dict[str, Any] | None:
    if not isinstance(item, dict):
        return None
    state = str(item.get("state") or "")
    status = _status_from_review_state(state)
    body = str(item.get("body") or "").strip()
    if not status and not body:
        return None
    author = item.get("author")
    source = "ai" if _author_is_bot(author) or _contains_ai_marker(body) else "human"
    if not body:
        body = f"{PR_STATUS_LABELS.get(status or 'needs_review', 'Needs review')} review recorded."
    return {
        "id": str(item.get("id") or item.get("submittedAt") or f"review-{index}"),
        "kind": "status" if status else ("ai_review" if source == "ai" else "human_review"),
        "source": source,
        "author": _author_login(author),
        "body": body,
        "createdAt": item.get("submittedAt") or item.get("createdAt"),
        "url": item.get("url"),
        "status": status,
    }


def _normalize_pr(item: dict[str, Any], cwd: Path, viewer_login: str | None) -> dict[str, Any]:
    number = int(item.get("number") or 0)
    title = str(item.get("title") or f"Pull request #{number}")
    status = _pr_status(item)
    check_summary, checks_failing = _check_summary(item.get("statusCheckRollup"))
    comments = [
        comment
        for comment in (_pr_comment(raw, index) for index, raw in enumerate(item.get("comments") or []))
        if comment is not None
    ]
    comments.extend(
        comment
        for comment in (_pr_review_comment(raw, index) for index, raw in enumerate(item.get("latestReviews") or []))
        if comment is not None
    )
    files = [
        file
        for file in (_pr_file(raw, index) for index, raw in enumerate(item.get("files") or []))
        if file is not None
    ]
    labels = [
        str(label.get("name") or "")
        for label in item.get("labels") or []
        if isinstance(label, dict) and str(label.get("name") or "").strip()
    ]
    author = _author_login(item.get("author"))
    risk = _risk_label(item, status, checks_failing)
    return {
        "id": f"pr-{number}",
        "project": cwd.name,
        "projectPath": str(cwd),
        "number": number,
        "title": title,
        "author": author,
        "branch": str(item.get("headRefName") or ""),
        "baseBranch": str(item.get("baseRefName") or ""),
        "updated": _relative_time_label(item.get("updatedAt")),
        "updatedAt": item.get("updatedAt"),
        "url": item.get("url"),
        "status": status,
        "statusLabel": PR_STATUS_LABELS.get(status, "Needs review"),
        "risk": risk,
        "checkSummary": check_summary,
        "description": _first_body_paragraph(item.get("body"), title),
        "labels": labels,
        "commentsCount": len(comments),
        "comments": comments,
        "files": files,
        "isMine": bool(viewer_login and author.lower() == viewer_login.lower()),
        "isFlagged": status in {"needs_review", "refused"} or risk == "High",
        "reviewDecision": item.get("reviewDecision") or None,
        "mergeState": item.get("mergeStateStatus") or item.get("mergeable") or None,
    }
